name: "ModTest"

on:
  workflow_call:
    inputs:
      workspace:
        required: true
        type: string
      github_server:
        required: true
        type: string
      github_org:
        required: true
        type: string
      mod_source:
        type: string
        required: true
      branch:
        type: string
        required: true
      workspace_branch:
        type: string
        required: false
        default: main
    secrets:
      TFE_TOKEN:
        required: true
      GH_TOKEN:
        required: true
env:
  GITHUB_OWNER: ${{ inputs.github_org }}
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  TFE_TOKEN: ${{ secrets.TFE_TOKEN }}
  
jobs:
  modtest:
    name: "Run modtest on target workspace"
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          persist-credentials: false
          token: ${{ secrets.GH_TOKEN }} # `GH_PAT` is a secret that contains your PAT

      - name: Checkout workspace repo
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.github_org }}/${{ inputs.workspace }}
          path: ${{ inputs.workspace }}
          ref: ${{ inputs.workspace_branch }}
          token: ${{ secrets.GH_TOKEN }} # `GH_PAT` is a secret that contains your PAT


      - name: Download Dependenices
        run: |
          stat .modtest_bin 2>/dev/null >/dev/null || mkdir .modtest_bin
          curl -sSL https://raw.githubusercontent.com/HappyPathway/centralized-actions/main/modtest -o .modtest_bin/modtest.py
          curl -sSL https://raw.githubusercontent.com/HappyPathway/centralized-actions/main/testall -o .modtest_bin/testall
          curl -sSL https://raw.githubusercontent.com/HappyPathway/centralized-actions/main/mod_versions -o .modtest_bin/mod_versions
          echo "PATH=${PATH}:${PWD}/.modtest_bin" >> $GITHUB_ENV 
          chmod +x .modtest_bin/*

      - name: testall
        run: |
          testall ${{ inputs.github_server }} ${{ inputs.github_org }} ${{ inputs.mod_source }} ${{ inputs.branch }}
          terraform plan
        working-directory: ${{ inputs.workspace }}
      
